# Generated by Django 4.0.5 on 2022-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_title_video_caption_pack_adults_pack_founded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='history',
            field=models.CharField(default='No info available', max_length=100),
        ),
        migrations.AddField(
            model_name='pack',
            name='img',
            field=models.CharField(default='no image', max_length=500),
        ),
    ]
