# Generated by Django 4.0.5 on 2022-06-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_pack_history_pack_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='link',
            field=models.CharField(default='no link', max_length=400),
        ),
    ]
