# Generated by Django 4.0.5 on 2022-06-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='caption',
            field=models.CharField(default='no caption', max_length=125),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='no video', upload_to='video/%y'),
        ),
    ]
