# Generated by Django 4.0.5 on 2022-06-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
    ]
