# Generated by Django 4.0.5 on 2022-06-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='link',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(default='no video', upload_to='video/%y'),
        ),
    ]
