# Generated by Django 4.0.5 on 2022-06-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_video_link_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.TextField(default='noting yet', max_length=2000),
        ),
    ]
