# Generated by Django 4.0.5 on 2022-06-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_story_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='history',
            field=models.TextField(default='No info available', max_length=1200),
        ),
    ]
